services:
  avitotech:
    build: .
    container_name: avitotech
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
        - internal
    init: true
    environment:
      DB_HOST: db

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - psql_vol:/var/lib/postgresql/data
    networks:
        - internal
volumes:
  psql_vol:

networks:
  internal:
